import { getRandomIndex } from "../utils";

const birthdayWishes = [
  "Wishing you a birthday that's as special as you are. May your day be filled with love, laughter, and lots of cake!",
  "Happy birthday to someone who is beautiful inside and out. May your day be filled with all the things that make you happy!",
  "Wishing you a year filled with love, laughter, and lots of new experiences. Happy birthday to someone who is always up for an adventure!",
  "May your birthday be filled with sunshine, rainbows, and lots of cake! Happy birthday to one of the coolest people I know!",
  "Wishing you a day filled with love, laughter, and lots of hugs. Happy birthday to someone who is always there for me no matter what!",
  "May your birthday be filled with all the things that make you smile. Happy birthday to someone who is smart, funny, and just plain awesome!",
  "Wishing you a year filled with happiness, love, and lots of success. Happy birthday to someone who makes the world a better place just by being in it!",
  "May your birthday be filled with all the things that make you happy. Happy birthday to someone who is always there to lend a helping hand!",
  "Wishing you a day filled with love, laughter, and lots of fun. Happy birthday to someone who is always up for a good time!",
  "May your birthday be filled with love, laughter, and lots of cake. Happy birthday to someone who is kind, caring, and always there for others!",
  "Wishing you a year filled with love, laughter, and lots of new opportunities. Happy birthday to someone who is always there to make me laugh!",
  "May your birthday be filled with all the things that make you smile. Happy birthday to someone who is always there to listen and offer advice!",
  "Wishing you a day filled with love, laughter, and lots of joy. Happy birthday to someone who is always there to lend an ear!",
  "May your birthday be filled with love, laughter, and lots of cake. Happy birthday to someone who is always up for a challenge!",
  "Wishing you a year filled with happiness, love, and lots of success. Happy birthday to someone who is always there to offer a helping hand!",
  "May your birthday be filled with all the things that make you happy. Happy birthday to someone who is always there to make me smile!",
  "Wishing you a day filled with love, laughter, and lots of blessings. Happy birthday to someone who is always there to offer a shoulder to cry on!",
  "May your birthday be filled with love, laughter, and lots of cake. Happy birthday to someone who is always up for a good laugh!",
  "Wishing you a year filled with love, laughter, and lots of new beginnings. Happy birthday to someone who is always there to make me happy!",
  "May your birthday be filled with all the things that make you smile. Happy birthday to someone who is always there to offer a helping hand!",
  "Wishing you a day filled with love, laughter, and lots of love. Happy birthday to someone who is always there to make me feel better!",
  "May your birthday be filled with all the things that make you happy. Happy birthday to someone who is always there to make me laugh!",
  "Wishing you a year filled with love, laughter, and lots of new adventures. Happy birthday to someone who is always there to lend an ear!",
  "Wishing you a day filled with love, laughter, and lots of sunshine. Happy birthday to someone who is always there to offer a helping hand!",
  "May your birthday be filled with all the things that make you smile. Happy birthday to someone who is always there to make me smile!",
  "May your birthday be filled with all the things that make you happy. Happy birthday to someone who is always there to make me feel better!",
  "Wishing you a day filled with love, laughter, and lots of love. Happy birthday to someone who is always there to make me laugh!",
  "May your birthday be filled with all the things that make you happy. Happy birthday to someone who is always there to lend an ear!",
  "Wishing you a year filled with love, laughter, and lots of new adventures. Happy birthday to someone who is always up for a challenge!",
  "Wishing you a day filled with joy and laughter!",
  "May your birthday be as bright and beautiful as you are!",
  "Here's to another year of incredible adventures!",
  "Happy birthday! May all your wishes come true!",
  "Wishing you health, happiness, and lots of love on your special day!",
  "May this year bring you success and fulfillment in all you do!",
  "Cheers to another year of amazing you!",
  "Sending you warmest birthday wishes and a big hug!",
  "May your day be filled with love, surprises, and all things nice!",
  "Happy birthday to someone who makes the world brighter!",
  "Wishing you a year ahead full of exciting opportunities!",
  "May the coming year be your best one yet!",
  "Here's to celebrating you and all the joy you bring!",
  "Happy birthday! May your day be as fantastic as you are!",
  "Wishing you a day filled with love, laughter, and unforgettable moments!",
  "May your birthday be the start of a year filled with good luck and happiness!",
  "Cheers to another year of growth, learning, and achievements!",
  "Sending you smiles, hugs, and all the best on your special day!",
  "May your heart be filled with happiness and your life with love!",
  "Happy birthday! May this year be your most extraordinary yet!",
  "Wishing you a day surrounded by friends, family, and lots of joy!",
  "May your birthday be the beginning of a year full of exciting surprises!",
  "Cheers to another 365 days of laughter, love, and adventure!",
  "Happy birthday to someone who deserves all the happiness in the world!",
  "Wishing you a year ahead filled with dreams fulfilled and goals achieved!",
  "May your day be as sweet and special as you are!",
  "Happy birthday! May your life be as colorful and bright as the candles on your cake!",
  "Wishing you success, health, and endless joy in the year ahead!",
  "Cheers to another year of making incredible memories!",
  "May your birthday be the key to unlocking new opportunities and experiences!",
  "Happy birthday! May your day be filled with love and laughter!",
  "Wishing you a year ahead filled with prosperity and positivity!",
  "May your birthday be the spark that ignites a year of amazing achievements!",
  "Cheers to another 365 days of laughter, love, and good times!",
  "Happy birthday! May your day be as fabulous as you are!",
  "Wishing you a year filled with exciting surprises and delightful moments!",
  "May your birthday be the beginning of a chapter filled with love and success!",
  "Cheers to another year of chasing dreams and creating beautiful memories!",
  "Happy birthday! May your day be filled with sunshine, smiles, and laughter!",
  "Wishing you a year ahead filled with love, joy, and endless possibilities!",
  "May your birthday be the launchpad for a year of incredible achievements!",
  "Cheers to another 365 days of making unforgettable memories!",
  "Happy birthday! May your day be as special as the person you are!",
  "Wishing you a year filled with love, laughter, and all your heart desires!",
  "May your birthday be the gateway to a year of wonderful experiences!",
  "Cheers to another year of embracing life's beautiful journey!",
  "Wishing you a day filled with joy, laughter, and all the things you love! Happy Birthday!",
  "May this year bring you closer to your dreams and fill your life with happiness. Happy Birthday!",
  "On your special day, may you be surrounded by love, positivity, and good vibes. Happy Birthday!",
  "Sending you warm wishes on your birthday. May this year be the best one yet!",
  "May your birthday be as bright and cheerful as your smile. Celebrate the amazing person you are!",
  "Here's to another year of adventures, laughter, and incredible memories. Happy Birthday!",
  "Wishing you a day filled with love, surprises, and everything you've been dreaming of. Happy Birthday!",
  "May your birthday be the start of a year filled with new accomplishments and endless joy. Cheers to you!",
  "Sending you my heartfelt wishes for a day filled with love, laughter, and all the things that make you happy. Happy Birthday!",
  "On your special day, may you be surrounded by good friends, loving family, and all the happiness in the world. Happy Birthday!",
  "May this year bring you success, good health, and all the happiness you deserve. Happy Birthday!",
  "Wishing you a day that's as sweet as the cake you'll be cutting and as joyful as the celebrations you'll be having. Happy Birthday!",
  "May your birthday be the beginning of a year filled with exciting opportunities and wonderful surprises. Happy Birthday!",
  "Here's to another year of amazing experiences, personal growth, and all the things that bring you joy. Happy Birthday!",
  "May this special day be just the beginning of a year filled with happy moments, great achievements, and new adventures. Happy Birthday!",
  "Sending you warm wishes for a day filled with love, laughter, and the company of those who matter most. Happy Birthday!",
  "On your birthday, may you be surrounded by love, laughter, and the warmth of good friends and family. Happy Birthday!",
  "Wishing you a year ahead filled with love, laughter, and all the success you deserve. Happy Birthday!",
  "May your birthday be the perfect blend of joy, surprises, and cherished moments. Cheers to another fantastic year!",
  "Here's to celebrating the incredible person you are and the wonderful journey that lies ahead. Happy Birthday!",
  "Wishing you a very happy birthday and a year filled with joy and happiness!",
  "May your birthday be filled with love, laughter, and lots of cake!",
  "Wishing you all the best on your special day and throughout the year.",
  "Happy birthday to someone who is smart, funny, and just plain awesome!",
  "May your birthday be as wonderful as you are!",
  "Wishing you a day filled with love, laughter, and lots of presents!",
  "Happy birthday to one of the coolest people I know!",
  "May your birthday be filled with sunshine, rainbows, and lots of cake!",
  "Wishing you a year filled with love, laughter, and lots of adventures!",
  "Happy birthday to someone who makes the world a better place just by being in it!",
  "May your birthday be filled with all the things that make you happy!",
  "Wishing you a day filled with love, laughter, and lots of hugs!",
  "Happy birthday to someone who is always there for me no matter what!",
  "Wishing you a year filled with happiness, love, and lots of success!",
  "Happy birthday to someone who is beautiful inside and out!",
  "May your birthday be filled with all the things that make you smile!",
  "Wishing you a day filled with love, laughter, and lots of surprises!",
  "Happy birthday to someone who is always up for an adventure!",
  "Wishing you a year filled with love, laughter, and lots of new experiences!",
  "Happy birthday to someone who is kind, caring, and always there for others!",
  "Wishing you a day filled with love, laughter, and lots of fun!",
  "Happy birthday to someone who is always there to lend a helping hand!",
  "Happy birthday to someone who is always up for a good time!",
  "Wishing you a day filled with love, laughter, and lots of memories!",
  "Happy birthday to someone who is always there to listen and offer advice!",
  "Wishing you a year filled with love, laughter, and lots of new opportunities!",
  "Happy birthday to someone who is always there to make me laugh!",
  "Wishing you a day filled with love, laughter, and lots of joy!",
  "Happy birthday to someone who is always there to lend an ear!",
  "Happy birthday to someone who is always up for a challenge!",
  "Wishing you a day filled with love, laughter, and lots of happiness!",
  "Happy birthday to someone who is always there to offer a helping hand!",
  "Wishing you a year filled with love, laughter, and lots of new adventures!",
  "Happy birthday to someone who is always there to make me smile!",
  "Wishing you a day filled with love, laughter, and lots of blessings!",
  "Happy birthday to someone who is always there to offer a shoulder to cry on!",
  "Happy birthday to someone who is always up for a good laugh!",
  "Wishing you a day filled with love, laughter, and lots of sunshine!",
  "Happy birthday to someone who is always there to make me feel better!",
  "Wishing you a year filled with love, laughter, and lots of new beginnings!",
  "Happy birthday to someone who is always there to make me happy!",
  "Wishing you a day filled with love, laughter, and lots of love!",
  "Wishing you a day filled with joy, laughter, and unforgettable moments!",
  "Happy birthday! May your heart be as full as your cake!",
  "Here's to another year of adventures and amazing memories!",
  "May your day be as bright and cheerful as your smile!",
  "Happy birthday! May your dreams take flight this year!",
  "Cheers to another 365 days of love, happiness, and success!",
  "Wishing you a year ahead filled with exciting surprises and opportunities!",
  "May your birthday be the start of a year full of blessings!",
  "Happy birthday! May your life be as sweet as your favorite cake!",
  "Here's to celebrating the wonderful person you are!",
  "May this year bring you closer to your dreams and aspirations!",
  "Wishing you a day filled with love, laughter, and all your favorite things!",
  "May your birthday be the spark that ignites a year of greatness!",
  "Cheers to another year of growth, learning, and joyous moments!",
  "Happy birthday! May your heart be as happy as it's ever been!",
  "Here's to another 365 days of making beautiful memories!",
  "Wishing you success, health, and all the happiness in the world!",
  "May your day be surrounded by friends, family, and love!",
  "Happy birthday! May your wishes come true in the coming year!",
  "May your birthday be the beginning of a chapter filled with joy!",
  "Cheers to another year of chasing dreams and creating magic!",
  "Here's to embracing the journey and savoring each moment!",
  "May your life be as colorful and bright as the candles on your cake!",
  "Wishing you a year filled with exciting adventures and achievements!",
  "Happy birthday! May your day be filled with sunshine and smiles!",
  "May your birthday be the key to unlocking new opportunities!",
  "Cheers to another year of laughter, love, and good times!",
  "Here's to celebrating the wonderful soul that is you!",
  "Happy birthday! May your day be surrounded by those who cherish you!",
  "May your birthday be the spark that lights up your dreams!",
  "Cheers to another 365 days of making memories that last a lifetime!",
  "Wishing you a day filled with surprises and delightful moments!",
  "Happy birthday! May your year be as special as you are to us!",
  "May your day be filled with love, laughter, and everything you adore!",
  "Here's to another year of growth, achievements, and pure happiness!",
  "Wishing you a year ahead filled with love, success, and positive vibes!",
  "Happy birthday! May your heart be light, and your spirit be free!",
  "May your birthday be the start of a chapter filled with triumphs!",
  "Cheers to another year of chasing dreams and reaching new heights!",
  "Here's to celebrating you and the incredible person you've become!",
  "Happy birthday! May your day be filled with love, joy, and cake!",
  "Wishing you a year ahead filled with laughter and prosperity!",
  "Cheers to another 365 days of making every moment count!",
  "Here's to a year of growth, success, and endless possibilities!",
  "May your day be surrounded by those who bring you happiness!",
  "Wishing you a year filled with love, laughter, and adventure!",
  "Happy birthday! May your heart be as full as your presents!",
  "May your birthday be the spark that sets your dreams on fire!",
  "Cheers to another year of discovering new joys and triumphs!",
  "Here's to embracing the journey and enjoying the ride!",
  "Wishing you a year ahead filled with love, success, and fulfillment!",
  "Happy birthday! May your day be as fabulous as your dreams!",
  "May your life be as bright and vibrant as your favorite colors!",
  "Cheers to another 365 days of making memories with those you love!",
  "Wishing you a day filled with surprises, smiles, and all your favorite things!",
  "Happy birthday! May your year be as extraordinary as you are!",
  "Here's to another year of learning, growing, and achieving greatness!",
  "May your birthday be the beginning of a chapter filled with joy and love!",
  "Cheers to another year of laughter, love, and unforgettable moments!",
  "Happy birthday! May your day be surrounded by the warmth of love!",
  "Wishing you a year ahead filled with exciting opportunities and adventures!",
  "May your heart be as happy as the laughter that fills the air on your birthday!",
  "Here's to celebrating you and all the uniqueness you bring to the world!",
  "Cheers to another year of chasing dreams and making them a reality!",
  "Happy birthday! May your day be as magical as the moments we share!",
  "May your birthday be the spark that leads to a year of triumphs!",
  "Wishing you a year ahead filled with love, happiness, and endless possibilities!",
  "Happy birthday! May your heart be as full as your favorite dessert!",
  "Here's to another 365 days of joy, laughter, and incredible experiences!",
  "May your day be surrounded by the love and warmth of those who care about you!",
  "Cheers to another year of growth, achievements, and unforgettable memories!",
  "Wishing you a year ahead filled with love, success, and all your heart desires!",
  "Happy birthday! May your day be filled with sunshine and positive vibes!",
  "May your birthday be the key to unlocking new levels of happiness and fulfillment!",
  "Here's to another year of making memories with those who matter most!",
  "Cheers to embracing life's beautiful journey and savoring every moment!",
  "Happy birthday! May your year be as bright as the candles on your cake!",
  "Wishing you a day filled with love, laughter, and all the things that make you smile!",
  "May your birthday be the spark that lights up the path to your dreams!",
  "Here's to celebrating you and the wonderful person you've become!",
  "May your heart be as light as the laughter that fills the air on your special day!",
  "Cheers to another 365 days of making beautiful memories with loved ones!",
  "Wishing you a year ahead filled with love, joy, and exciting adventures!",
  "Happy birthday! May your day be surrounded by the warmth of cherished friendships!",
  "May your birthday be the beginning of a chapter filled with success and triumphs!",
  "Here's to another year of learning, growing, and becoming even more amazing!",
  "Cheers to embracing the journey and creating a life filled with happiness!",
  "Wishing you a day filled with surprises, smiles, and the company of loved ones!",
  "Happy birthday! May your year be as fabulous as the celebration itself!",
  "May your heart be as full as the love that surrounds you on your special day!",
  "Here's to another 365 days of joy, laughter, and making unforgettable memories!",
  "Cheers to another year of chasing dreams and reaching new heights of success!",
  "Wishing you a year ahead filled with love, laughter, and endless possibilities!",
  "Happy birthday! May your day be as incredible as the person you are!",
];

export default function useWish() {
  return birthdayWishes[getRandomIndex];
}
